_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 2
                - 3
                - 41
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.8
            "5": 0.19.0
            "8":
                - 3
                - 5
            "12": 0.19.0
            "13": windows-amd64
batch_size:
    value: 16
epochs:
    value: 10
img_size:
    value: 640
learning_rate:
    value: 0.01
